# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hello.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'hello.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhello.proto\"J\n\tInputInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\x12\n\nis_married\x18\x03 \x01(\x08\x12\x0e\n\x06salary\x18\x04 \x01(\x03\";\n\x0fOutputStatement\x12\x14\n\x0cintroduction\x18\x01 \x01(\t\x12\x12\n\nother_info\x18\x02 \x01(\t2@\n\nHelloSayer\x12\x32\n\x12SpeakPersonDetails\x12\n.InputInfo\x1a\x10.OutputStatementb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INPUTINFO']._serialized_start=15
  _globals['_INPUTINFO']._serialized_end=89
  _globals['_OUTPUTSTATEMENT']._serialized_start=91
  _globals['_OUTPUTSTATEMENT']._serialized_end=150
  _globals['_HELLOSAYER']._serialized_start=152
  _globals['_HELLOSAYER']._serialized_end=216
# @@protoc_insertion_point(module_scope)
