// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: router/router.proto

package router

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      int32                  `protobuf:"varint,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     int32                  `protobuf:"varint,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_router_router_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_router_router_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_router_router_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetLatitude() int32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Point) GetLongitude() int32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type Rectangle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lo            *Point                 `protobuf:"bytes,1,opt,name=lo,proto3" json:"lo,omitempty"`
	Hi            *Point                 `protobuf:"bytes,2,opt,name=hi,proto3" json:"hi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rectangle) Reset() {
	*x = Rectangle{}
	mi := &file_router_router_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rectangle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rectangle) ProtoMessage() {}

func (x *Rectangle) ProtoReflect() protoreflect.Message {
	mi := &file_router_router_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rectangle.ProtoReflect.Descriptor instead.
func (*Rectangle) Descriptor() ([]byte, []int) {
	return file_router_router_proto_rawDescGZIP(), []int{1}
}

func (x *Rectangle) GetLo() *Point {
	if x != nil {
		return x.Lo
	}
	return nil
}

func (x *Rectangle) GetHi() *Point {
	if x != nil {
		return x.Hi
	}
	return nil
}

type Feature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Location      *Point                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Feature) Reset() {
	*x = Feature{}
	mi := &file_router_router_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feature) ProtoMessage() {}

func (x *Feature) ProtoReflect() protoreflect.Message {
	mi := &file_router_router_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feature.ProtoReflect.Descriptor instead.
func (*Feature) Descriptor() ([]byte, []int) {
	return file_router_router_proto_rawDescGZIP(), []int{2}
}

func (x *Feature) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Feature) GetLocation() *Point {
	if x != nil {
		return x.Location
	}
	return nil
}

type RouteNote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Point                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteNote) Reset() {
	*x = RouteNote{}
	mi := &file_router_router_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteNote) ProtoMessage() {}

func (x *RouteNote) ProtoReflect() protoreflect.Message {
	mi := &file_router_router_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteNote.ProtoReflect.Descriptor instead.
func (*RouteNote) Descriptor() ([]byte, []int) {
	return file_router_router_proto_rawDescGZIP(), []int{3}
}

func (x *RouteNote) GetLocation() *Point {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *RouteNote) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RouteSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PointCount    int32                  `protobuf:"varint,1,opt,name=point_count,json=pointCount,proto3" json:"point_count,omitempty"`
	FeatureCount  int32                  `protobuf:"varint,2,opt,name=feature_count,json=featureCount,proto3" json:"feature_count,omitempty"`
	Distance      int32                  `protobuf:"varint,3,opt,name=distance,proto3" json:"distance,omitempty"`
	ElapsedTime   int32                  `protobuf:"varint,4,opt,name=elapsed_time,json=elapsedTime,proto3" json:"elapsed_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteSummary) Reset() {
	*x = RouteSummary{}
	mi := &file_router_router_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteSummary) ProtoMessage() {}

func (x *RouteSummary) ProtoReflect() protoreflect.Message {
	mi := &file_router_router_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteSummary.ProtoReflect.Descriptor instead.
func (*RouteSummary) Descriptor() ([]byte, []int) {
	return file_router_router_proto_rawDescGZIP(), []int{4}
}

func (x *RouteSummary) GetPointCount() int32 {
	if x != nil {
		return x.PointCount
	}
	return 0
}

func (x *RouteSummary) GetFeatureCount() int32 {
	if x != nil {
		return x.FeatureCount
	}
	return 0
}

func (x *RouteSummary) GetDistance() int32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *RouteSummary) GetElapsedTime() int32 {
	if x != nil {
		return x.ElapsedTime
	}
	return 0
}

var File_router_router_proto protoreflect.FileDescriptor

const file_router_router_proto_rawDesc = "" +
	"\n" +
	"\x13router/router.proto\x12\x06router\"A\n" +
	"\x05Point\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x05R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x05R\tlongitude\"I\n" +
	"\tRectangle\x12\x1d\n" +
	"\x02lo\x18\x01 \x01(\v2\r.router.PointR\x02lo\x12\x1d\n" +
	"\x02hi\x18\x02 \x01(\v2\r.router.PointR\x02hi\"H\n" +
	"\aFeature\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\blocation\x18\x02 \x01(\v2\r.router.PointR\blocation\"P\n" +
	"\tRouteNote\x12)\n" +
	"\blocation\x18\x01 \x01(\v2\r.router.PointR\blocation\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x93\x01\n" +
	"\fRouteSummary\x12\x1f\n" +
	"\vpoint_count\x18\x01 \x01(\x05R\n" +
	"pointCount\x12#\n" +
	"\rfeature_count\x18\x02 \x01(\x05R\ffeatureCount\x12\x1a\n" +
	"\bdistance\x18\x03 \x01(\x05R\bdistance\x12!\n" +
	"\felapsed_time\x18\x04 \x01(\x05R\velapsedTime2\xe3\x01\n" +
	"\n" +
	"RouteGuide\x12.\n" +
	"\n" +
	"GetFeature\x12\r.router.Point\x1a\x0f.router.Feature\"\x00\x126\n" +
	"\fListFeatures\x12\x11.router.Rectangle\x1a\x0f.router.Feature\"\x000\x01\x126\n" +
	"\vRecordRoute\x12\r.router.Point\x1a\x14.router.RouteSummary\"\x00(\x01\x125\n" +
	"\tRouteChat\x12\x11.router.RouteNote\x1a\x11.router.RouteNote(\x010\x01B=Z;github.com/idiotcoffee/gRPC-learning/routing-example/routerb\x06proto3"

var (
	file_router_router_proto_rawDescOnce sync.Once
	file_router_router_proto_rawDescData []byte
)

func file_router_router_proto_rawDescGZIP() []byte {
	file_router_router_proto_rawDescOnce.Do(func() {
		file_router_router_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_router_router_proto_rawDesc), len(file_router_router_proto_rawDesc)))
	})
	return file_router_router_proto_rawDescData
}

var file_router_router_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_router_router_proto_goTypes = []any{
	(*Point)(nil),        // 0: router.Point
	(*Rectangle)(nil),    // 1: router.Rectangle
	(*Feature)(nil),      // 2: router.Feature
	(*RouteNote)(nil),    // 3: router.RouteNote
	(*RouteSummary)(nil), // 4: router.RouteSummary
}
var file_router_router_proto_depIdxs = []int32{
	0, // 0: router.Rectangle.lo:type_name -> router.Point
	0, // 1: router.Rectangle.hi:type_name -> router.Point
	0, // 2: router.Feature.location:type_name -> router.Point
	0, // 3: router.RouteNote.location:type_name -> router.Point
	0, // 4: router.RouteGuide.GetFeature:input_type -> router.Point
	1, // 5: router.RouteGuide.ListFeatures:input_type -> router.Rectangle
	0, // 6: router.RouteGuide.RecordRoute:input_type -> router.Point
	3, // 7: router.RouteGuide.RouteChat:input_type -> router.RouteNote
	2, // 8: router.RouteGuide.GetFeature:output_type -> router.Feature
	2, // 9: router.RouteGuide.ListFeatures:output_type -> router.Feature
	4, // 10: router.RouteGuide.RecordRoute:output_type -> router.RouteSummary
	3, // 11: router.RouteGuide.RouteChat:output_type -> router.RouteNote
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_router_router_proto_init() }
func file_router_router_proto_init() {
	if File_router_router_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_router_router_proto_rawDesc), len(file_router_router_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_router_router_proto_goTypes,
		DependencyIndexes: file_router_router_proto_depIdxs,
		MessageInfos:      file_router_router_proto_msgTypes,
	}.Build()
	File_router_router_proto = out.File
	file_router_router_proto_goTypes = nil
	file_router_router_proto_depIdxs = nil
}
