// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: greeter/greeter.proto

package greeter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GreetPerson_SayHi_FullMethodName = "/greeter.GreetPerson/SayHi"
)

// GreetPersonClient is the client API for GreetPerson service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreetPersonClient interface {
	SayHi(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type greetPersonClient struct {
	cc grpc.ClientConnInterface
}

func NewGreetPersonClient(cc grpc.ClientConnInterface) GreetPersonClient {
	return &greetPersonClient{cc}
}

func (c *greetPersonClient) SayHi(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, GreetPerson_SayHi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreetPersonServer is the server API for GreetPerson service.
// All implementations must embed UnimplementedGreetPersonServer
// for forward compatibility.
type GreetPersonServer interface {
	SayHi(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedGreetPersonServer()
}

// UnimplementedGreetPersonServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGreetPersonServer struct{}

func (UnimplementedGreetPersonServer) SayHi(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SayHi not implemented")
}
func (UnimplementedGreetPersonServer) mustEmbedUnimplementedGreetPersonServer() {}
func (UnimplementedGreetPersonServer) testEmbeddedByValue()                     {}

// UnsafeGreetPersonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreetPersonServer will
// result in compilation errors.
type UnsafeGreetPersonServer interface {
	mustEmbedUnimplementedGreetPersonServer()
}

func RegisterGreetPersonServer(s grpc.ServiceRegistrar, srv GreetPersonServer) {
	// If the following call panics, it indicates UnimplementedGreetPersonServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GreetPerson_ServiceDesc, srv)
}

func _GreetPerson_SayHi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetPersonServer).SayHi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreetPerson_SayHi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetPersonServer).SayHi(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GreetPerson_ServiceDesc is the grpc.ServiceDesc for GreetPerson service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GreetPerson_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "greeter.GreetPerson",
	HandlerType: (*GreetPersonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHi",
			Handler:    _GreetPerson_SayHi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greeter/greeter.proto",
}
